### ISSUE TITLE
FACTURACIÓN: Evitar agregar articulo dos veces

### ISSUE THREAD

**Issue by Fabro83** [afliw/ferresys#13]
Cuando se agregue un articulo que ya está en la lista, que sume la cantidad al que ya estaba y reemplace el descuento por el nuevo o algo así

**Comment by afliw** [comment]
@Fabro83 ¿"O algo así"? ¿Que manera de escribir es esa? Un poco de profesionalismo por favor...

**Comment by Fabro83** [comment]
Este issue ya había quedado cerrado ¬¬
