### ISSUE TITLE
PERSONA: PerPersonaSeeder no funciona

### ISSUE THREAD

**Issue by afliw** [afliw/ferresys#8]

**Comment by Fabro83** [comment]
![image](https://user-images.githubusercontent.com/16551732/42725263-7a3c6160-8757-11e8-8957-ad2f654a655a.png)

**Comment by Fabro83** [comment]
Recién probado, está fucionando. Que problema te tira?

**Comment by Fabro83** [comment]
Te sigue tirando problemas?

**Comment by Fabro83** [comment]
Vuelto a probar, funciona correctamente, si te vuelvce a tirar error, re abrilo
