### ISSUE TITLE
PROVEEDOR: Bug creación de nuevo proveedor

### ISSUE THREAD

**Issue by afliw** [afliw/ferresys#9]
Con persona física tira error al crear (key constraint). Revisar datos y consultas a base de datos.

Con persona jurídica, la validación de campos requeridos no permite crear (apellido y fecha de nacimiento se exigen).

**Comment by Fabro83** [comment]
![image](https://user-images.githubusercontent.com/16551732/42725284-b92207b8-8757-11e8-9bf7-8b882381181d.png)
En la base se ve que no son requeridos, debe ser alguna validación
